services:
  trash-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: trash-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: 1234
    ports:
      - "5672:5672"
      - "15672:15672"
