services:
  trash-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: trash-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: 1234
    ports:
      - "5672:5672"
      - "15672:15672"
  trash-redis:
    image: redis:latest
    container_name: trash-redis
    ports:
      - "6379:6379"
    restart: always
