INSERT INTO trash_category (ko, en) VALUES ('가구류', 'Furniture');
INSERT INTO trash_category (ko, en) VALUES ('고철류', 'Scrap Metal');
INSERT INTO trash_category (ko, en) VALUES ('불연성 종량제', 'Non-burnable Waste');
INSERT INTO trash_category (ko, en) VALUES ('비닐류', 'Vinyl');
INSERT INTO trash_category (ko, en) VALUES ('스티로폼류', 'Styrofoam');
INSERT INTO trash_category (ko, en) VALUES ('유리병류', 'Glass Bottles');
INSERT INTO trash_category (ko, en) VALUES ('전용함', 'Dedicated Collection Box');
INSERT INTO trash_category (ko, en) VALUES ('종량제', 'General Waste Bag');
INSERT INTO trash_category (ko, en) VALUES ('종이류', 'Paper');
INSERT INTO trash_category (ko, en) VALUES ('캔류', 'Cans');
INSERT INTO trash_category (ko, en) VALUES ('폐가전제품', 'Waste Electronics');
INSERT INTO trash_category (ko, en) VALUES ('플라스틱류', 'Plastic');