insert into trash_category (ko, en) values ('가구류', 'Furniture');
insert into trash_category (ko, en) values ('고철류', 'Scrap Metal');
insert into trash_category (ko, en) values ('불연성 종량제', 'Non-burnable Waste');
insert into trash_category (ko, en) values ('비닐류', 'Vinyl');
insert into trash_category (ko, en) values ('스티로폼류', 'Styrofoam');
insert into trash_category (ko, en) values ('유리병류', 'Glass Bottles');
insert into trash_category (ko, en) values ('전용함', 'Dedicated Collection Box');
insert into trash_category (ko, en) values ('종량제', 'General Waste Bag');
insert into trash_category (ko, en) values ('종이류', 'Paper');
insert into trash_category (ko, en) values ('캔류', 'Cans');
insert into trash_category (ko, en) values ('폐가전제품', 'Waste Electronics');
insert into trash_category (ko, en) values ('플라스틱류', 'Plastic');