server:
  port: 8080

spring:
  profiles:
    active: dev
    include: secret

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc.time_zone: Asia/Seoul

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

kakao:
  auth: https://kauth.kakao.com
  api: https://kapi.kakao.com

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

rabbitmq:
  request-queue-name: analysis.request.queue
  result-queue-name: analysis.result.queue
  exchange: analysis.exchange
  request-routing-key: analysis.request
  result-routing-key: analysis.result

island:
  model:
    base-url: https://image.sonyk9919.store:20024