spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${custom.prod.db.url}
    username: ${custom.prod.db.username}
    password: ${custom.prod.db.password}
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      data-locations:
        - classpath:/db/category.sql
        - classpath:/db/subcategory.sql
        - classpath:/db/taxonomy.sql
        - classpath:/db/disposal.sql
        - classpath:/db/disposal_category.sql
        - classpath:/db/disposal_subcategory.sql
        - classpath:/db/analysis-example.sql
        - classpath:/db/trash-example.sql

  data:
    redis:
      host: ${custom.redis.host}
      port: ${custom.redis.port}

  rabbitmq:
    host: ${custom.prod.rabbitmq.host}
    port: ${custom.prod.rabbitmq.port}
    username: ${custom.prod.rabbitmq.username}
    password: ${custom.prod.rabbitmq.password}
    listener:
      simple:
        retry:
          enabled: true
          max-retries: 2
        default-requeue-rejected: false

file:
  upload-dir: ${custom.prod.uploadDir}
  external-path: ${custom.prod.externalPath}

analysis:
  fastApi:
    url: ${custom.prod.fastApiUrl}

jwt:
  secret: ${custom.jwt.secret}
  expiry:
    access: ${custom.jwt.access:3600}
    refresh: ${custom.jwt.refresh:604800}

security:
  cookie:
    sameSite: Lax
    domain: .sonyk9919.store

  cors:
    origins:
      - https://sonyk9919.store:20024
      - https://api.sonyk9919.store:20024
      - http://localhost:3000
      - http://localhost:5173
    methods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
    headers:
      - Content-Type
    path: /**
    maxAge: 3600

management:
  endpoints:
    web:
      exposure:
        include: health