spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${custom.prod.db.url}
    username: ${custom.prod.db.username}
    password: ${custom.prod.db.password}
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${custom.prod.redis.host}
      port: ${custom.prod.redis.port}

file:
  upload-dir: ${custom.prod.uploadDir}

analysis:
  fastApi:
    url: ${custom.prod.fastApiUrl}

jwt:
  secret: ${custom.jwt.secret}